/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import Script from 'next/script';
import Head from 'next/head'
import Image from 'next/image'
import { MdChevronLeft, MdChevronRight } from "react-icons/md";
import Link from 'next/link';
import { IoIosArrowDropright } from "react-icons/io";
import { MdOutlineKeyboardArrowLeft, MdOutlineKeyboardArrowRight } from "react-icons/md";

import { useState, useEffect } from 'react';
import { Transition } from 'mdi-material-ui';

export default function Home() {
  const addImages = [
    'ADD/ADD.jpg',
    'ADD/aeroplane3.jpg',
    'ADD/LIMI.png',
    'ADD/3.jpg',
    'ADD/ADD1.jpg'

  ]



  const [current, setcurrent] = useState(0)

  const previousSlide = async () => {
    if (current === 0) setcurrent(addImages.length - 1)
    else {
      setcurrent(current - 1)
    }
  }

  const nextSlide = async () => {
    if (current === addImages.length - 1) setcurrent(0)
    else {
      setcurrent(current + 1)
    }
  }

  useEffect(() => {
    const timer = setTimeout(() => {
      nextSlide()
    }, 4000);

    return () => {
      clearTimeout(timer);
    }
  }, [current])


  return (
    <div>
      <Head>
        <title>Sangam Bharat Site for Buying Animals | Agriculture Equipment | Pets| Animal Accessories</title>
        <meta name="description" content="sangambharat.com | An ecommerce for Animals and pets | Generated by Sangam Infotec" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />

        <meta name="description" content="Online platform where you can sale animals like cat | dog |cows| horse| birds| buffalo| calf| sheep| goat| pets" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <div className="w-full tab:px-2 px-1 border    mt-2 my-0 mx-auto">
        <div className="  bg-white rounded-md  pb-1  justify-center ">

          <div id="slider" className='tab:max-h-[130px] medium:max-h-max sm:max-h-[105px] relative flex flex-row  justify-start md:justify-start lg:justify-center xl:justify-center  z-auto scrollbar-hide overflow-x-scroll scroll whitespace-nowrap scroll-smooth'>

            <Link href={'/animals'}>
              <div className='md:w-[130px] md:mx-8 md:h-[80px] w-[95px] h-[100px] inline-block p-2 md:p-2 m-1  md:ml-5 cursor-pointer hover:scale-105 ease-in-out duration-300 bg-white  px-2 md:pt-3  rounded-lg'>
                <img src={'animal.jpg'} className='w-full  md:h-[70px] h-[50px] rounded-sm' alt='animal' ></img>
                <p className="text-center mt-2 md:m-1 md:mt-3 text-sm font-semibold">Animals</p>
                
              </div>
            </Link>
            <Link href={'/'}><div className='md:w-[130px] relative  md:mx-8 md:h-[120px] w-[95px] h-[100px] inline-block p-2 md:p-2 m-1  md:ml-5 cursor-pointer hover:scale-105 ease-in-out duration-300 bg-white  px-2 md:pt-3  rounded-lg'>
              <img src={'birds.jpg'} className='w-full md:h-[70px] opacity-40 mb-2  h-[50px] rounded-sm' alt='birds' ></img>
              <span className=' text-red-600 py-0.5   text-center  md:ml-1 text-sm font-semibold  px-2 rounded-md  text-[14px]'>Coming soon!</span>
            </div></Link>
            <Link href={'/'}><div className='md:w-[130px]  md:mx-8 md:h-[80px] w-[95px] h-[100px] inline-block p-2 md:p-2 m-1  md:ml-5 cursor-pointer hover:scale-105 ease-in-out duration-300 bg-white  px-2 md:pt-3  rounded-lg'>
              <img src={'fermer.jpg'} className='w-full md:h-[70px] opacity-40 mb-2 h-[50px] rounded-sm' alt='farming' ></img>
              <span className=' text-red-600 py-0.5   text-center  md:ml-1 text-sm font-semibold  px-2 rounded-md  text-[14px]'>Coming soon!</span>
            </div></Link>
            <Link href={'/'}><div className='md:w-[130px]  md:mx-8 md:h-[120px] w-[95px] h-[100px] inline-block p-2 md:p-2 m-1  md:ml-5 cursor-pointer hover:scale-105 ease-in-out duration-300 bg-white  px-2 md:pt-3  rounded-lg'>
              <img src={'hira.png'} className='bg-white w-full md:h-[70px] opacity-40 mb-2 h-[50px] rounded-sm' alt='pet food' ></img>
              <span className=' text-red-600 py-0.5   text-center  md:ml-1 text-sm font-semibold  px-2 rounded-md  text-[14px]'>Coming soon!</span>
            </div>
            </Link>

            <Link href={'/'}> <div className='md:w-[130px]  md:mx-8 md:h-[120px] w-[95px] h-[100px] inline-block p-2 md:p-2 m-1  md:ml-5 cursor-pointer hover:scale-105 ease-in-out duration-300 bg-white  px-2 md:pt-3  rounded-lg'>
              <img src={'ferti.jpg'} className='w-full md:h-[70px] opacity-40 mb-2 h-[50px] rounded-sm' alt='Fertilizers' ></img>
              <span className=' text-red-600 py-0.5   text-center  md:ml-1 text-sm font-semibold  px-2 rounded-md  text-[14px]'>Coming soon!</span>
            </div>
            </Link>
            <Link href={'/'}><div className='md:w-[130px]  md:mx-8 md:h-[120px] w-[95px] h-[100px] inline-block p-2 md:p-2 m-1  md:ml-5 cursor-pointer hover:scale-105 ease-in-out duration-300 bg-white  px-2 md:pt-3  rounded-lg'>
              <img src={'pesti.jpg'} className='w-full md:h-[70px] opacity-40 mb-2 h-[50px] rounded-sm' alt='Pesticides' ></img>
              <span className=' text-red-600 py-0.5   text-center  md:ml-1 text-sm font-semibold  px-2 rounded-md  text-[14px]'>Coming soon!</span>
            </div></Link>


          </div>

        </div>
      </div>












    <div className=" relative  hidden tab:flex   px-2    tab:my-2  mx-auto ">
      <div className='relative ' >
        <div className={`flex transition ease-out duration-500 xl:h-auto  `} style={{ Transition: '100px' }}>
          <img src={addImages[current]} className='md:h-56 xl:h-auto max-h-56  hover:ease-in-out  lg:h-52 border rounded-md sm:h-40 h-24  w-screen' alt="fdsm" />
         
        </div>

        <div className=' absolute inset-0  w-full items-center  justify-between   flex text-white text-xl'>
          <button className='bg-white rounded-sm text-slate-800 px-2 py-8 ' onClick={previousSlide}><MdOutlineKeyboardArrowLeft></MdOutlineKeyboardArrowLeft></button>
          <button className='bg-white rounded-sm text-slate-800 px-2 py-8 ' onClick={nextSlide}><MdOutlineKeyboardArrowRight /></button>
        </div>
        <div className="absolute bottom-1 sm:py-4 flex justify-center gap-2 w-full">
          {addImages.map((s, i) => {
            return (
            
                <div
                  onClick={() => { setcurrent(i) }}
                  key={i}
                  className={`rounded-full bottom-0 cursor-pointer w-2 h-2 ${i === current ? "bg-gray-300" : "bg-white"}`}>
                </div>
            )
          })}
        </div>
      </div>
    </div>
    

          



      {/* <section className="text-gray-600 body-font">
  <div className="container px-5 py-2 mx-auto flex flex-wrap">
 
    <div className="flex flex-wrap md:-m-2 -m-1">
      <div className="flex flex-wrap w-1/2">
        <div className="md:p-2 p-1 w-1/2">
          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/500x300"/>
        </div>
        <div className="md:p-2 p-1 w-1/2">
          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/501x301"/>
        </div>
        <div className="md:p-2 p-1 w-full">
          <img alt="gallery" className="w-full h-full object-cover object-center block" src="https://dummyimage.com/600x360"/>
        </div>
      </div>
      <div className="flex flex-wrap w-1/2">
        <div className="md:p-2 p-1 w-full">
          <img alt="gallery" className="w-full h-full object-cover object-center block" src="https://dummyimage.com/601x361"/>
        </div>
        <div className="md:p-2 p-1 w-1/2">
          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/502x302"/>
        </div>
        <div className="md:p-2 p-1 w-1/2">
          <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/503x303"/>
        </div>
      </div>
    </div>
  </div>
</section>  */}

      <section className="text-gray-600 mx-auto body-font overflow-hidden">
        <div className="container   medium:px-2 mx-auto">

          <div className="flex flex-wrap w-full ">
            <div className="p-4  medium:w-1/4 md:1/3 tab:w-1/2 w-full ">
              <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
                <Link href={'/animals'}><img src="ADD/Animals.png" className='h-[390px] medium:h-[350px] w-full' alt="" />
                </Link>     </div>
            </div>
            <div className="p-4 medium:w-1/4 md:1/3 tab:w-1/2 w-full">
              <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
                <Link href={'/'}><img src="ADD/Birds.png" className='h-[390px] medium:h-[350px] w-full' alt="" />
                </Link>     </div>
            </div>
            <div className="p-4 medium:w-1/4 md:1/3 tab:w-1/2 w-full">
              <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
                <Link href={'/'}><img src="ADD/TULK.png" className='h-[390px] medium:h-[350px] w-full' alt="" />
                </Link>     </div>
            </div>
            <div className="p-4 medium:w-1/4 md:1/3 tab:w-1/2 w-full">
              <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
                <Link href={'/animals'}><img src="ADD/COW.png" className='h-[390px] medium:h-[350px] w-full' alt="" />
                </Link>     </div>
            </div>
            <div className="p-4 medium:w-1/4 md:1/3 tab:w-1/2 w-full">
              <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
                <Link href={'/'}><img src="ADD/SULK.png" className='h-[390px] medium:h-[350px] w-full' alt="" />
                </Link>     </div>
            </div>
            <div className="p-4 medium:w-1/4 md:1/3 tab:w-1/2 w-full">
              <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
                <Link href={'/'}><img src="ADD/Birds.png" className='h-[390px] medium:h-[350px] w-full' alt="" />
                </Link>     </div>
            </div>
            <div className="p-4 medium:w-1/4 md:1/3 tab:w-1/2 w-full">
              <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
                <Link href={'/'}><img src="ADD/Animals.png" className='h-[390px] medium:h-[350px] w-full' alt="" />
                </Link>     </div>
            </div>
            <div className="p-4 medium:w-1/4 md:1/3 tab:w-1/2 w-full">
              <div className="h-full  rounded-lg  flex flex-col relative overflow-hidden">
                <Link href={'/'}><img src="ADD/Birds.png" className='h-[390px] medium:h-[350px] w-full' alt="" />
                </Link>     </div>
            </div>





          </div>
        </div>
      </section>

    </div>
  )
}
